name: dart_template
description: "Adsplatter's Dart template for new projects."
version: 1.0.0

repository: https://github.com/adsplatter/dart-template
homepage: https://github.com/adsplatter/dart-template
issue_tracker: https://github.com/adsplatter/dart-template/issues

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
